kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: kubewarden
  namespace: fleet-default
spec:
  repo: https://github.com/bgulla/fleet-public.git
  branch: main
  targets:
  - kubewarden: true
  paths:
  - kubewarden/base
#  - kubewarden/policies

